Add missing <sys/types.h> includes
<sys/types.h> is needed for the definition of off_t, otherwise building
with uClibc fails with:

In file included from cfgfile.c:17:0:
cfgfile.h:25:87: error: unknown type name ‘off_t’
 int archive_read_all_data(struct archive *a, struct archive_entry *ae, char **buffer, off_t max_size, off_t *size_read);
                                                                                       ^
cfgfile.h:25:103: error: unknown type name ‘off_t’
 int archive_read_all_data(struct archive *a, struct archive_entry *ae, char **buffer, off_t max_size, off_t *size_read);

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>