Fix uclibc build
Without sys/types.h the build breaks with errors like this:

parse_file.h:28:5: error: unknown type name ‘off_t’
     off_t *map;
     ^